### ISSUE TITLE
Specify service port in TrafficSplit

### ISSUE THREAD

**Issue by stefanprodan** [deislabs/smi-spec#14]
A Kubernetes service can expose more than one port. To support such a service the TrafficSplit could have an optional field in the backend spec: 

ClusterIP with multiple ports:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-primary
spec:
  type: ClusterIP
  selector:
    app: frontend-primary
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - name: grpc
      port: 9090
      protocol: TCP
      targetPort: grpc
```

TrafficSplit for HTTP:
```yaml
apiVersion: v1beta1
kind: TrafficSplit
metadata:
  name: frontend
spec:
  service: frontend
  backends:
  - service: frontend-primary
    port: 8080
    weight: 900m
  - service: frontend-canary
    port: 8080
    weight: 100m
```
