### ISSUE TITLE
TrafficSplit Question: Are weights in resource.Quantity?

### ISSUE THREAD

**Issue by surajssd** [deislabs/smi-spec#31]
```yaml
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: my-weights
spec:
  # The root service that clients use to connect to the destination application.
  service: numbers
  # Services inside the namespace with their own selectors, endpoints and configuration.
  backends:
  - service: one
    # Identical to resources, 1 = 1000m
    weight: 10m
  - service: two
    weight: 100m
  - service: three
    weight: 1500m
```

- Are the weights defined in the above `TrafficSplit` object, Kubernetes [`resource.Quantity`](https://github.com/kubernetes/apimachinery/blob/7d8f8feb49c5e20ddbf3cf45f945122f8a4e3b05/pkg/api/resource/quantity.go#L88). ?
- Also does weight support all the various suffixes supported by `resource.Quantity`? Or is it that the spec just supports `m` a.k.a `milli` right now ?

If it's full-fledged Quantity then I think https://github.com/deislabs/smi-sdk-go/pull/6 makes sense.
